
#ifndef GETAWAY_INPUTTYPE_H
#define GETAWAY_INPUTTYPE_H


enum class inputType{
    OPTIONSELECTIONINPUTLOBBY = 0,
    MESSAGESTRING = 1,
    OPTIONSELECTIONINPUTGAME = 2,
    GAMEPERFORMTURN = 4,
    HOMEMAIN = 5,
    HOMEIPADDRESS = 6,
    HOMECONNECTTOPROBEREPLYSERVER = 7,
    HOMESTARTSERVER = 8,
    HOMEASSIGNSERVERNAME = 9,
    HOMEJOINSERVER = 10,
    HOMECONNECTTINGTOSERVER = 11,
    HOMECLIENTNAMEJOININGSERVER = 12,
    HOMECLIENTNAMESTARTINGSERVER = 13,
    HOMEGAMERULES = 14,
    HOMEABOUT = 15,
    SERVERLOBBYONEPLAYER = 16,
    SERVERLOBBYTWOORMOREPLAYERS = 17,
    HOMESELECTGAMESTARTINGSERVER = 18,
    GB_SIMPLENONTURNINPUT = 19,
    GB_FIRSTTURNOFTHEROUND = 22,
    GB_PERFORMFIRSTTURNSELECTCARDS = 23,
    GB_PERFORMFIRSTTURNSELECTDECKSUITTYPE = 24,
    GB_NORMALTURNOFTHEROUND = 19,
    GB_PERFORMNORMALTURNSELECTCARDS = 20
};

#endif //GETAWAY_INPUTTYPE_H
