
#ifndef GETAWAY_INPUTTYPE_H
#define GETAWAY_INPUTTYPE_H


enum class inputType{
    OPTIONSELECTIONINPUTLOBBY = 0,
    MESSAGESTRING = 1,
    OPTIONSELECTIONINPUTGAME = 2,
    GAMEPERFORMTURN = 4,
    HOMEMAIN = 5,
    HOMEIPADDRESS = 6,
    HOMECONNECTTOPROBEREPLYSERVER = 7,
    HOMESTARTSERVER = 8,
    HOMEASSIGNSERVERNAME = 9,
    HOMEJOINSERVER = 10,
    HOMECONNECTTINGTOSERVER = 11,
    HOMECLIENTNAMEJOININGSERVER = 12,
    HOMECLIENTNAMESTARTINGSERVER = 13,
    HOMEGAMERULES = 14,
    HOMEABOUT = 15,
    SERVERLOBBYONEPLAYER = 16,
    SERVERLOBBYTWOORMOREPLAYERS = 17
};

#endif //GETAWAY_INPUTTYPE_H
