
#ifndef GETAWAY_INPUTTYPE_HPP
#define GETAWAY_INPUTTYPE_HPP

//In this file, you will define inputType values for your game. For Game Foo, these will start with GF_
enum class inputType{
    OPTIONSELECTIONINPUTLOBBY = 0,
    MESSAGESTRING = 1,
    OPTIONSELECTIONINPUTGAME = 2,
    GAMEPERFORMTURN = 3,
    HOMEMAIN = 4,
    HOMEIPADDRESS = 5,
    HOMECONNECTTOPROBEREPLYSERVER = 6,
    HOMESTARTSERVER = 7,
    HOMEASSIGNSERVERNAME = 8,
    HOMEJOINSERVER = 9,
    HOMECONNECTTINGTOSERVER = 10,
    HOMECLIENTNAMEJOININGSERVER = 11,
    HOMECLIENTNAMESTARTINGSERVER = 12,
    HOMEGAMERULES = 13,
    HOMEABOUT = 14,
    SERVERLOBBYONEPLAYER = 15,
    SERVERLOBBYTWOORMOREPLAYERS = 16,
    HOMESELECTGAMESTARTINGSERVER = 17,
    GB_SIMPLENONTURNINPUT = 18, //GB means Game Bluff
    GB_FIRSTTURNOFTHEROUND = 19,
    GB_PERFORMFIRSTTURNSELECTCARDS = 20,
    GB_PERFORMFIRSTTURNSELECTDECKSUITTYPE = 21,
    GB_NORMALTURNOFTHEROUND = 22,
    GB_PERFORMNORMALTURNSELECTCARDS = 23
};

#endif //GETAWAY_INPUTTYPE_HPP
